# Generated by Django 2.1 on 2020-11-07 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Age',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='aciklama',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='companies',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='experience',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='major',
            field=models.CharField(default='Computer Science', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nameSurname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='profile',
            name='oduller',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='speciality',
            field=models.CharField(default='Python', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Istanbul', max_length=100),
        ),
    ]
