# Generated by Django 2.1 on 2020-11-07 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seniorjn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
